/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MIMXRT685S
package_id: MIMXRT685SFVKB
mcu_data: ksdk2_0
processor_version: 25.06.10
board: MIMXRT685-EVK
pin_labels:
- {pin_num: H2, pin_signal: PIO0_3/FC0_CTS_SDA_SSEL0/CTIMER0_MAT3/FC1_SSEL2/SEC_PIO0_3, label: 'J1[3]/J36[4]/J45[58]', identifier: I2C_SDA_DAC}
- {pin_num: J1, pin_signal: PIO0_4/FC0_RTS_SCL_SSEL1/CTIMER_INP0/FC1_SSEL3/CMP0_OUT/SEC_PIO0_4, label: 'J1[5]/J45[60]', identifier: I2C_SCL_DAC}
- {pin_num: D7, pin_signal: PIO0_17/FC2_CTS_SDA_SSEL0/SCT0_GPI3/SCT0_OUT3/CTIMER2_MAT3/FC5_SSEL2/SEC_PIO0_17, label: 'J28[9]/J30[5]/J47[8]/U6[6]', identifier: FC2_I2C_SDA;I2C_SDA_DAC}
- {pin_num: B7, pin_signal: PIO0_18/FC2_RTS_SCL_SSEL1/SCT0_GPI6/SCT0_OUT6/CTIMER_INP4/FC5_SSEL3/SEC_PIO0_18, label: 'J28[10]/J30[6]/U6[4]', identifier: FC2_I2C_SCL;I2C_SCL_DAC}
- {pin_num: G15, pin_signal: PIO1_1/FC4_SSEL2/SCT0_GPI2/SCT0_OUT8/CTIMER1_MAT0, label: 'FLEXSPI_B_DATA, 2'}
- {pin_num: B5, pin_signal: PIO1_8/FC5_SSEL2/SCT0_GPI6/CTIMER_INP12/CTIMER1_MAT2/ADC0_4, label: 'J27[8]/J45[20]', identifier: ADC04A}
- {pin_num: B1, pin_signal: PIO1_9/FC5_SSEL3/SCT0_GPI7/UTICK_CAP1/CTIMER1_MAT3/ADC0_12, label: 'J28[1]', identifier: ADC04B}
- {pin_num: N1, pin_signal: PIO1_13/HS_SPI_MOSI/CTIMER2_MAT2/FLEXSPI0B_DATA2, label: 'U19[C4]', identifier: QSPI_B_DATA2;GPIO_REV_IND_3}
- {pin_num: T9, pin_signal: PIO1_18/FLEXSPI0A_SCLK/SCT0_GPI0/CTIMER3_MAT3, label: 'U108[B2]', identifier: PSRAM_CLK;FLEXSPIOA_CLK}
- {pin_num: T4, pin_signal: PIO1_19/FLEXSPI0A_SS0_N/SCT0_OUT0/CTIMER4_MAT0, label: 'U108[A3]', identifier: PSRAM_CE;FLEXSPIOA_CS}
- {pin_num: T5, pin_signal: PIO1_20/FLEXSPI0A_DATA0/SCT0_GPI1/CTIMER4_MAT1, label: 'U108[D3]', identifier: PSRAM_ADQ0;FLEXSPIOA_DATA0}
- {pin_num: U5, pin_signal: PIO1_21/FLEXSPI0A_DATA1/SCT0_OUT1/CTIMER4_MAT2, label: 'U108[D2]', identifier: PSRAM_ADQ1;FLEXSPIOA_DATA1}
- {pin_num: P6, pin_signal: PIO1_22/FLEXSPI0A_DATA2/SCT0_GPI2/CTIMER4_MAT3, label: 'U108[C4]', identifier: PSRAM_ADQ2;FLEXSPIOA_DATA2}
- {pin_num: P7, pin_signal: PIO1_23/FLEXSPI0A_DATA3/SCT0_OUT2/CTIMER_INP8, label: 'U108[D4]', identifier: PSRAM_ADQ3;FLEXSPIOA_DATA3}
- {pin_num: T7, pin_signal: PIO1_24/FLEXSPI0A_DATA4/SCT0_GPI3, label: 'U108[D5]', identifier: PSRAM_ADQ4;FLEXSPIOA_DATA4}
- {pin_num: U7, pin_signal: PIO1_25/FLEXSPI0A_DATA5/SCT0_OUT3, label: 'U108[E3]', identifier: PSRAM_ADQ5;FLEXSPIOA_DATA5}
- {pin_num: R7, pin_signal: PIO1_26/FLEXSPI0A_DATA6/SCT0_GPI4, label: 'U108[E2]', identifier: PSRAM_ADQ6;FLEXSPIOA_DATA6}
- {pin_num: T8, pin_signal: PIO1_27/FLEXSPI0A_DATA7/SCT0_OUT4, label: 'U108[E1]', identifier: PSRAM_ADQ7;FLEXSPIOA_DATA7}
- {pin_num: U9, pin_signal: PIO1_28/FLEXSPI0A_DQS/SCT0_GPI5, label: 'U108[C3]', identifier: PSRAM_DQS;FLEXSPIOA_DQS}
- {pin_num: U13, pin_signal: PIO2_5/SD0_D4/SCT0_OUT3, label: SD_DAT4, identifier: GPIO2_5}
- {pin_num: U15, pin_signal: PIO2_6/SD0_D5/SCT0_GPI4/CTIMER1_MAT0, label: SD_DAT5, identifier: GPIO2_6}
- {pin_num: U16, pin_signal: PIO2_7/SD0_D6/SCT0_GPI5/CTIMER1_MAT1, label: SD_DAT6, identifier: GPIO2_7}
- {pin_num: U17, pin_signal: PIO2_8/SD0_D7/SCT0_OUT4/CTIMER1_MAT2, label: SD_DAT7, identifier: GPIO2_8}
- {pin_num: T3, pin_signal: PIO2_12/SCT0_OUT6/CTIMER2_MAT2, label: 'J1[4]', identifier: LED_GREEN}
- {pin_num: T1, pin_signal: PIO2_13/SCT0_OUT7/CTIMER2_MAT3/CMP0_OUT, label: 'J1[2]', identifier: LED_RED}
- {pin_num: C1, pin_signal: PIO2_14/SCT0_OUT8/CTIMER_INP1/CMP0_A, label: 'J1[9]', identifier: FLASH_RSTIN}
- {pin_num: E2, pin_signal: PIO2_15/SCT0_OUT9/CLKIN/CMP0_D, label: 'J1[8]', identifier: FLASH_PWR_DIS}
- {pin_num: R1, pin_signal: PIO2_16/PDM_CLK01, label: 'U40[4]/U41[4]/PDM_CLK01_OnBoard', identifier: PDM_CLK01;FLASH_CRR_GAIN}
- {pin_num: U1, pin_signal: PIO2_17/PDM_CLK23/FLEXSPI0B_DATA4, label: 'U19[D5]', identifier: QSPI_B_DATA4;CPU_RESET_EN}
- {pin_num: R2, pin_signal: PIO2_18/PDM_CLK45/FLEXSPI0B_DATA5, label: 'U19[E3]', identifier: QSPI_B_DATA5;RSTOUT}
- {pin_num: T2, pin_signal: PIO2_19/PDM_CLK67/FLEXSPI0B_SS0_N, label: 'U19[C2]', identifier: QSPI_B_CS0;RSTOUT_EN}
- {pin_num: U2, pin_signal: PIO2_20/PDM_DATA01, label: 'U40[1]/U41[1]/PDM_DATA01_OnBoard', identifier: PDM_DATA01;LED_BLUE}
- {pin_num: R3, pin_signal: PIO2_21/PDM_DATA23/CTIMER_INP14/FLEXSPI0B_SS1_N, label: 'J31[6]', identifier: INT}
- {pin_num: P3, pin_signal: PIO2_22/PDM_DATA45/FLEXSPI0B_DATA6, label: 'U19[E2]', identifier: QSPI_B_DATA6;GPIO_REV_IND_1}
- {pin_num: P5, pin_signal: PIO2_23/PDM_DATA67/FLEXSPI0B_DATA7, label: 'U19[E1]', identifier: QSPI_B_DATA7;GPIO_REV_IND_2}
- {pin_num: L16, pin_signal: PIO2_24/SWO/GPIO_INT_BMAT, label: 'U7[12]', identifier: SWO;USER_BUTTON}
- {pin_num: D2, pin_signal: VREFP, label: 'JP10[2]', identifier: ADC0_VREF}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iopctl.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitFlexSPI0APins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: G4, peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_2/FC0_RXD_SDA_MOSI_DATA/CTIMER0_MAT2/I2S_BRIDGE_DATA_IN/SEC_PIO0_2, pupdena: disabled,
    pupdsel: pullDown, ibena: enabled, slew_rate: normal, drive: normal, amena: disabled, odena: disabled, iiena: disabled}
  - {pin_num: G2, peripheral: FLEXCOMM0, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_1/FC0_TXD_SCL_MISO_WS/CTIMER0_MAT1/I2S_BRIDGE_WS_IN/SEC_PIO0_1, pupdena: disabled,
    pupdsel: pullDown, ibena: disabled, slew_rate: normal, drive: normal, amena: disabled, odena: disabled, iiena: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPins(void)
{

    const uint32_t DEBUG_UART_TXD = (/* Pin is configured as FC0_TXD_SCL_MISO_WS */
                                     IOPCTL_PIO_FUNC1 |
                                     /* Disable pull-up / pull-down function */
                                     IOPCTL_PIO_PUPD_DI |
                                     /* Enable pull-down function */
                                     IOPCTL_PIO_PULLDOWN_EN |
                                     /* Disable input buffer function */
                                     IOPCTL_PIO_INBUF_DI |
                                     /* Normal mode */
                                     IOPCTL_PIO_SLEW_RATE_NORMAL |
                                     /* Normal drive */
                                     IOPCTL_PIO_FULLDRIVE_DI |
                                     /* Analog mux is disabled */
                                     IOPCTL_PIO_ANAMUX_DI |
                                     /* Pseudo Output Drain is disabled */
                                     IOPCTL_PIO_PSEDRAIN_DI |
                                     /* Input function is not inverted */
                                     IOPCTL_PIO_INV_DI);
    /* PORT0 PIN1 (coords: G2) is configured as FC0_TXD_SCL_MISO_WS */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITPINS_DEBUG_UART_TXD_PORT, BOARD_INITPINS_DEBUG_UART_TXD_PIN, DEBUG_UART_TXD);

    const uint32_t DEBUG_UART_RXD = (/* Pin is configured as FC0_RXD_SDA_MOSI_DATA */
                                     IOPCTL_PIO_FUNC1 |
                                     /* Disable pull-up / pull-down function */
                                     IOPCTL_PIO_PUPD_DI |
                                     /* Enable pull-down function */
                                     IOPCTL_PIO_PULLDOWN_EN |
                                     /* Enables input buffer function */
                                     IOPCTL_PIO_INBUF_EN |
                                     /* Normal mode */
                                     IOPCTL_PIO_SLEW_RATE_NORMAL |
                                     /* Normal drive */
                                     IOPCTL_PIO_FULLDRIVE_DI |
                                     /* Analog mux is disabled */
                                     IOPCTL_PIO_ANAMUX_DI |
                                     /* Pseudo Output Drain is disabled */
                                     IOPCTL_PIO_PSEDRAIN_DI |
                                     /* Input function is not inverted */
                                     IOPCTL_PIO_INV_DI);
    /* PORT0 PIN2 (coords: G4) is configured as FC0_RXD_SDA_MOSI_DATA */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITPINS_DEBUG_UART_RXD_PORT, BOARD_INITPINS_DEBUG_UART_RXD_PIN, DEBUG_UART_RXD);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitFlexSPI0APins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: T9, peripheral: FLEXSPI, signal: FLEXSPI_A_SCLK, pin_signal: PIO1_18/FLEXSPI0A_SCLK/SCT0_GPI0/CTIMER3_MAT3, identifier: FLEXSPIOA_CLK, pupdsel: pullDown,
    ibena: enabled}
  - {pin_num: U9, peripheral: FLEXSPI, signal: FLEXSPI_A_DQS, pin_signal: PIO1_28/FLEXSPI0A_DQS/SCT0_GPI5, identifier: FLEXSPIOA_DQS, pupdena: enabled, pupdsel: pullUp,
    ibena: enabled}
  - {pin_num: T4, peripheral: FLEXSPI, signal: FLEXSPI_A_SS0_B, pin_signal: PIO1_19/FLEXSPI0A_SS0_N/SCT0_OUT0/CTIMER4_MAT0, identifier: FLEXSPIOA_CS, ibena: enabled}
  - {pin_num: T5, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA0, pin_signal: PIO1_20/FLEXSPI0A_DATA0/SCT0_GPI1/CTIMER4_MAT1, identifier: FLEXSPIOA_DATA0, ibena: enabled}
  - {pin_num: U5, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA1, pin_signal: PIO1_21/FLEXSPI0A_DATA1/SCT0_OUT1/CTIMER4_MAT2, identifier: FLEXSPIOA_DATA1, ibena: enabled}
  - {pin_num: P6, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA2, pin_signal: PIO1_22/FLEXSPI0A_DATA2/SCT0_GPI2/CTIMER4_MAT3, identifier: FLEXSPIOA_DATA2, ibena: enabled}
  - {pin_num: R7, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA6, pin_signal: PIO1_26/FLEXSPI0A_DATA6/SCT0_GPI4, identifier: FLEXSPIOA_DATA6, ibena: enabled}
  - {pin_num: U7, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA5, pin_signal: PIO1_25/FLEXSPI0A_DATA5/SCT0_OUT3, identifier: FLEXSPIOA_DATA5, ibena: enabled}
  - {pin_num: T7, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA4, pin_signal: PIO1_24/FLEXSPI0A_DATA4/SCT0_GPI3, identifier: FLEXSPIOA_DATA4, ibena: enabled}
  - {pin_num: P7, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA3, pin_signal: PIO1_23/FLEXSPI0A_DATA3/SCT0_OUT2/CTIMER_INP8, identifier: FLEXSPIOA_DATA3, ibena: enabled}
  - {pin_num: T8, peripheral: FLEXSPI, signal: FLEXSPI_A_DATA7, pin_signal: PIO1_27/FLEXSPI0A_DATA7/SCT0_OUT4, identifier: FLEXSPIOA_DATA7, ibena: enabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFlexSPI0APins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitFlexSPI0APins(void)
{

    const uint32_t FLEXSPIOA_CLK = (/* Pin is configured as FLEXSPI0A_SCLK */
                                    IOPCTL_PIO_FUNC1 |
                                    /* Disable pull-up / pull-down function */
                                    IOPCTL_PIO_PUPD_DI |
                                    /* Enable pull-down function */
                                    IOPCTL_PIO_PULLDOWN_EN |
                                    /* Enables input buffer function */
                                    IOPCTL_PIO_INBUF_EN |
                                    /* Normal mode */
                                    IOPCTL_PIO_SLEW_RATE_NORMAL |
                                    /* Normal drive */
                                    IOPCTL_PIO_FULLDRIVE_DI |
                                    /* Analog mux is disabled */
                                    IOPCTL_PIO_ANAMUX_DI |
                                    /* Pseudo Output Drain is disabled */
                                    IOPCTL_PIO_PSEDRAIN_DI |
                                    /* Input function is not inverted */
                                    IOPCTL_PIO_INV_DI);
    /* PORT1 PIN18 (coords: T9) is configured as FLEXSPI0A_SCLK */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CLK_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CLK_PIN, FLEXSPIOA_CLK);

    const uint32_t FLEXSPIOA_CS = (/* Pin is configured as FLEXSPI0A_SS0_N */
                                   IOPCTL_PIO_FUNC1 |
                                   /* Disable pull-up / pull-down function */
                                   IOPCTL_PIO_PUPD_DI |
                                   /* Enable pull-down function */
                                   IOPCTL_PIO_PULLDOWN_EN |
                                   /* Enables input buffer function */
                                   IOPCTL_PIO_INBUF_EN |
                                   /* Normal mode */
                                   IOPCTL_PIO_SLEW_RATE_NORMAL |
                                   /* Normal drive */
                                   IOPCTL_PIO_FULLDRIVE_DI |
                                   /* Analog mux is disabled */
                                   IOPCTL_PIO_ANAMUX_DI |
                                   /* Pseudo Output Drain is disabled */
                                   IOPCTL_PIO_PSEDRAIN_DI |
                                   /* Input function is not inverted */
                                   IOPCTL_PIO_INV_DI);
    /* PORT1 PIN19 (coords: T4) is configured as FLEXSPI0A_SS0_N */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CS_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CS_PIN, FLEXSPIOA_CS);

    const uint32_t FLEXSPIOA_DATA0 = (/* Pin is configured as FLEXSPI0A_DATA0 */
                                      IOPCTL_PIO_FUNC1 |
                                      /* Disable pull-up / pull-down function */
                                      IOPCTL_PIO_PUPD_DI |
                                      /* Enable pull-down function */
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      /* Enables input buffer function */
                                      IOPCTL_PIO_INBUF_EN |
                                      /* Normal mode */
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      /* Normal drive */
                                      IOPCTL_PIO_FULLDRIVE_DI |
                                      /* Analog mux is disabled */
                                      IOPCTL_PIO_ANAMUX_DI |
                                      /* Pseudo Output Drain is disabled */
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      /* Input function is not inverted */
                                      IOPCTL_PIO_INV_DI);
    /* PORT1 PIN20 (coords: T5) is configured as FLEXSPI0A_DATA0 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA0_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA0_PIN, FLEXSPIOA_DATA0);

    const uint32_t FLEXSPIOA_DATA1 = (/* Pin is configured as FLEXSPI0A_DATA1 */
                                      IOPCTL_PIO_FUNC1 |
                                      /* Disable pull-up / pull-down function */
                                      IOPCTL_PIO_PUPD_DI |
                                      /* Enable pull-down function */
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      /* Enables input buffer function */
                                      IOPCTL_PIO_INBUF_EN |
                                      /* Normal mode */
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      /* Normal drive */
                                      IOPCTL_PIO_FULLDRIVE_DI |
                                      /* Analog mux is disabled */
                                      IOPCTL_PIO_ANAMUX_DI |
                                      /* Pseudo Output Drain is disabled */
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      /* Input function is not inverted */
                                      IOPCTL_PIO_INV_DI);
    /* PORT1 PIN21 (coords: U5) is configured as FLEXSPI0A_DATA1 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA1_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA1_PIN, FLEXSPIOA_DATA1);

    const uint32_t FLEXSPIOA_DATA2 = (/* Pin is configured as FLEXSPI0A_DATA2 */
                                      IOPCTL_PIO_FUNC1 |
                                      /* Disable pull-up / pull-down function */
                                      IOPCTL_PIO_PUPD_DI |
                                      /* Enable pull-down function */
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      /* Enables input buffer function */
                                      IOPCTL_PIO_INBUF_EN |
                                      /* Normal mode */
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      /* Normal drive */
                                      IOPCTL_PIO_FULLDRIVE_DI |
                                      /* Analog mux is disabled */
                                      IOPCTL_PIO_ANAMUX_DI |
                                      /* Pseudo Output Drain is disabled */
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      /* Input function is not inverted */
                                      IOPCTL_PIO_INV_DI);
    /* PORT1 PIN22 (coords: P6) is configured as FLEXSPI0A_DATA2 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA2_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA2_PIN, FLEXSPIOA_DATA2);

    const uint32_t FLEXSPIOA_DATA3 = (/* Pin is configured as FLEXSPI0A_DATA3 */
                                      IOPCTL_PIO_FUNC1 |
                                      /* Disable pull-up / pull-down function */
                                      IOPCTL_PIO_PUPD_DI |
                                      /* Enable pull-down function */
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      /* Enables input buffer function */
                                      IOPCTL_PIO_INBUF_EN |
                                      /* Normal mode */
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      /* Normal drive */
                                      IOPCTL_PIO_FULLDRIVE_DI |
                                      /* Analog mux is disabled */
                                      IOPCTL_PIO_ANAMUX_DI |
                                      /* Pseudo Output Drain is disabled */
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      /* Input function is not inverted */
                                      IOPCTL_PIO_INV_DI);
    /* PORT1 PIN23 (coords: P7) is configured as FLEXSPI0A_DATA3 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA3_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA3_PIN, FLEXSPIOA_DATA3);

    const uint32_t FLEXSPIOA_DATA4 = (/* Pin is configured as FLEXSPI0A_DATA4 */
                                      IOPCTL_PIO_FUNC1 |
                                      /* Disable pull-up / pull-down function */
                                      IOPCTL_PIO_PUPD_DI |
                                      /* Enable pull-down function */
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      /* Enables input buffer function */
                                      IOPCTL_PIO_INBUF_EN |
                                      /* Normal mode */
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      /* Normal drive */
                                      IOPCTL_PIO_FULLDRIVE_DI |
                                      /* Analog mux is disabled */
                                      IOPCTL_PIO_ANAMUX_DI |
                                      /* Pseudo Output Drain is disabled */
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      /* Input function is not inverted */
                                      IOPCTL_PIO_INV_DI);
    /* PORT1 PIN24 (coords: T7) is configured as FLEXSPI0A_DATA4 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA4_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA4_PIN, FLEXSPIOA_DATA4);

    const uint32_t FLEXSPIOA_DATA5 = (/* Pin is configured as FLEXSPI0A_DATA5 */
                                      IOPCTL_PIO_FUNC1 |
                                      /* Disable pull-up / pull-down function */
                                      IOPCTL_PIO_PUPD_DI |
                                      /* Enable pull-down function */
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      /* Enables input buffer function */
                                      IOPCTL_PIO_INBUF_EN |
                                      /* Normal mode */
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      /* Normal drive */
                                      IOPCTL_PIO_FULLDRIVE_DI |
                                      /* Analog mux is disabled */
                                      IOPCTL_PIO_ANAMUX_DI |
                                      /* Pseudo Output Drain is disabled */
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      /* Input function is not inverted */
                                      IOPCTL_PIO_INV_DI);
    /* PORT1 PIN25 (coords: U7) is configured as FLEXSPI0A_DATA5 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA5_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA5_PIN, FLEXSPIOA_DATA5);

    const uint32_t FLEXSPIOA_DATA6 = (/* Pin is configured as FLEXSPI0A_DATA6 */
                                      IOPCTL_PIO_FUNC1 |
                                      /* Disable pull-up / pull-down function */
                                      IOPCTL_PIO_PUPD_DI |
                                      /* Enable pull-down function */
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      /* Enables input buffer function */
                                      IOPCTL_PIO_INBUF_EN |
                                      /* Normal mode */
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      /* Normal drive */
                                      IOPCTL_PIO_FULLDRIVE_DI |
                                      /* Analog mux is disabled */
                                      IOPCTL_PIO_ANAMUX_DI |
                                      /* Pseudo Output Drain is disabled */
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      /* Input function is not inverted */
                                      IOPCTL_PIO_INV_DI);
    /* PORT1 PIN26 (coords: R7) is configured as FLEXSPI0A_DATA6 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA6_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA6_PIN, FLEXSPIOA_DATA6);

    const uint32_t FLEXSPIOA_DATA7 = (/* Pin is configured as FLEXSPI0A_DATA7 */
                                      IOPCTL_PIO_FUNC1 |
                                      /* Disable pull-up / pull-down function */
                                      IOPCTL_PIO_PUPD_DI |
                                      /* Enable pull-down function */
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      /* Enables input buffer function */
                                      IOPCTL_PIO_INBUF_EN |
                                      /* Normal mode */
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      /* Normal drive */
                                      IOPCTL_PIO_FULLDRIVE_DI |
                                      /* Analog mux is disabled */
                                      IOPCTL_PIO_ANAMUX_DI |
                                      /* Pseudo Output Drain is disabled */
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      /* Input function is not inverted */
                                      IOPCTL_PIO_INV_DI);
    /* PORT1 PIN27 (coords: T8) is configured as FLEXSPI0A_DATA7 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA7_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA7_PIN, FLEXSPIOA_DATA7);

    const uint32_t FLEXSPIOA_DQS = (/* Pin is configured as FLEXSPI0A_DQS */
                                    IOPCTL_PIO_FUNC1 |
                                    /* Enable pull-up / pull-down function */
                                    IOPCTL_PIO_PUPD_EN |
                                    /* Enable pull-up function */
                                    IOPCTL_PIO_PULLUP_EN |
                                    /* Enables input buffer function */
                                    IOPCTL_PIO_INBUF_EN |
                                    /* Normal mode */
                                    IOPCTL_PIO_SLEW_RATE_NORMAL |
                                    /* Normal drive */
                                    IOPCTL_PIO_FULLDRIVE_DI |
                                    /* Analog mux is disabled */
                                    IOPCTL_PIO_ANAMUX_DI |
                                    /* Pseudo Output Drain is disabled */
                                    IOPCTL_PIO_PSEDRAIN_DI |
                                    /* Input function is not inverted */
                                    IOPCTL_PIO_INV_DI);
    /* PORT1 PIN28 (coords: U9) is configured as FLEXSPI0A_DQS */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DQS_PORT, BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DQS_PIN, FLEXSPIOA_DQS);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
