/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FC0_RXD_SDA_MOSI_DATA (coord G4), JP21[2]/U28[3]/U9[13]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_DEBUG_UART_RXD_PERIPHERAL FLEXCOMM0           /*!<@brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_RXD_SIGNAL RXD_SDA_MOSI_DATA       /*!<@brief Signal name */
#define BOARD_INITPINS_DEBUG_UART_RXD_PORT 0U                        /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RXD_PIN 2U                         /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RXD_PIN_MASK (1U << 2U)            /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name FC0_TXD_SCL_MISO_WS (coord G2), J16[1]/U27[3]/U9[12]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_DEBUG_UART_TXD_PERIPHERAL FLEXCOMM0         /*!<@brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_TXD_SIGNAL TXD_SCL_MISO_WS       /*!<@brief Signal name */
#define BOARD_INITPINS_DEBUG_UART_TXD_PORT 0U                      /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TXD_PIN 1U                       /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TXD_PIN_MASK (1U << 1U)          /*!<@brief PORT pin mask */
                                                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PULLUP_EN 0x20u        /*!<@brief Enable pull-up function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_PUPD_EN 0x10u          /*!<@brief Enable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FLEXSPI0A_SCLK (coord T9), U108[B2]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CLK_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CLK_SIGNAL FLEXSPI_A_SCLK
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CLK_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CLK_PIN 18U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CLK_PIN_MASK (1U << 18U)
/* @} */

/*! @name FLEXSPI0A_DQS (coord U9), U108[C3]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DQS_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DQS_SIGNAL FLEXSPI_A_DQS
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DQS_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DQS_PIN 28U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DQS_PIN_MASK (1U << 28U)
/* @} */

/*! @name FLEXSPI0A_SS0_N (coord T4), U108[A3]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CS_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CS_SIGNAL FLEXSPI_A_SS0_B    /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CS_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CS_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_CS_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name FLEXSPI0A_DATA0 (coord T5), U108[D3]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA0_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA0_SIGNAL FLEXSPI_A_DATA0
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA0_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA0_PIN 20U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA0_PIN_MASK (1U << 20U)
/* @} */

/*! @name FLEXSPI0A_DATA1 (coord U5), U108[D2]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA1_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA1_SIGNAL FLEXSPI_A_DATA1
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA1_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA1_PIN 21U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA1_PIN_MASK (1U << 21U)
/* @} */

/*! @name FLEXSPI0A_DATA2 (coord P6), U108[C4]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA2_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA2_SIGNAL FLEXSPI_A_DATA2
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA2_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA2_PIN 22U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA2_PIN_MASK (1U << 22U)
/* @} */

/*! @name FLEXSPI0A_DATA6 (coord R7), U108[E2]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA6_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA6_SIGNAL FLEXSPI_A_DATA6
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA6_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA6_PIN 26U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA6_PIN_MASK (1U << 26U)
/* @} */

/*! @name FLEXSPI0A_DATA5 (coord U7), U108[E3]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA5_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA5_SIGNAL FLEXSPI_A_DATA5
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA5_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA5_PIN 25U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA5_PIN_MASK (1U << 25U)
/* @} */

/*! @name FLEXSPI0A_DATA4 (coord T7), U108[D5]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA4_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA4_SIGNAL FLEXSPI_A_DATA4
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA4_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA4_PIN 24U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA4_PIN_MASK (1U << 24U)
/* @} */

/*! @name FLEXSPI0A_DATA3 (coord P7), U108[D4]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA3_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA3_SIGNAL FLEXSPI_A_DATA3
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA3_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA3_PIN 23U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA3_PIN_MASK (1U << 23U)
/* @} */

/*! @name FLEXSPI0A_DATA7 (coord T8), U108[E1]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA7_PERIPHERAL FLEXSPI
/*!
 * @brief Signal name */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA7_SIGNAL FLEXSPI_A_DATA7
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA7_PORT 1U
/*!
 * @brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA7_PIN 27U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFLEXSPI0APINS_FLEXSPIOA_DATA7_PIN_MASK (1U << 27U)
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFlexSPI0APins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
